### ISSUE TITLE
Refactor route discovery

### ISSUE THREAD

**Issue by goshlanguage** [goshlanguage/cerulean#15]
The way we populate echo with routes should be automatic.

Let's have a way where each services routes are automatically populated/discovered. 

This should be taken from the current open PR:
https://github.com/goshlanguage/cerulean/pull/12/files

**Comment by jessemillar** [comment]
The more I look into this, the more I begin to think there's not a cleaner solution than the one currently in PR 12. Go doesn't have a clean way (native or via library) to find types that implement an interface at runtime (which felt like the easiest solution in theory because we could just get a list of implementations of `services/interface.go` and then add them to the Echo router) and adding routes to a global map of some sort still requires manual instantiation/calling of a "add this to the global map" function.
